### ISSUE TITLE
Desktop.duplex-content component

### ISSUE THREAD

**Issue by bogdankatrych** [VS-work/vs-website#10]
![selection_046](https://cloud.githubusercontent.com/assets/17002555/19113404/1b1123f8-8b12-11e6-9790-45fefdab767d.png)

Needs to implement `Illustrated content component`:
- Image
- Background
- Formatted html

**Comment by otelnov** [comment]
https://github.com/VS-work/vs-website/issues/14

**Comment by SergeyKuryatnick** [comment]
Tested

Comments:
Text have some grammatical issues, but text are nor approved yet. So new issues for text is unneccessary
