### ISSUE TITLE
Desktop. Insert icon in browser tab

### ISSUE THREAD

**Issue by SergeyKuryatnick** [VS-work/vs-website#100]
**WTR:**
1. Open https://vs-work.github.io/#/
2. Pay attention at icon on the browser tab

**Result:** Icon is absent
**Expected result:** Displayed icon from original site Valor-software.com
![1476878713039](https://cloud.githubusercontent.com/assets/19388643/19518039/6ac3664e-960d-11e6-9b36-d988f2d3ba70.jpg)

**Comment by SergeyKuryatnick** [comment]
Bogdan, provide please source of this icon

**Comment by bogdankatrych** [comment]
@SergeyKuryatnick 
![fav](https://cloud.githubusercontent.com/assets/17002555/19520212/1af4cfee-9618-11e6-8af1-08a1e8e54736.png)

**Comment by SergeyKuryatnick** [comment]
Fixed
