### ISSUE TITLE
Mobile. Contact page. Elements displayed incorrectly

### ISSUE THREAD

**Issue by SergeyKuryatnick** [VS-work/vs-website#110]
**WTR:**
1. Open https://vs-work.github.io/#/contact
2. Pay attention at page elements

**Result:** Elements displayed incorrectly
**Expected result:** Elements displayed correctly in mobile version
![1476959623178](https://cloud.githubusercontent.com/assets/19388643/19556480/feea5afa-96c9-11e6-87e4-7cd85bd0b857.jpg)

**Comment by daniloff200** [comment]
Duplicated #97 
Close this plz :D @bogdankatrych
