### ISSUE TITLE
Desktop.Enhancements according with suggestions

### ISSUE THREAD

**Issue by bogdankatrych** [VS-work/vs-website#122]
- Delete animation and border from button "Contact". Just underlining
![selection_085](https://cloud.githubusercontent.com/assets/17002555/19685143/abd35918-9ac3-11e6-9a32-8c1a5384507d.png)

- Auto-scrolling has to be more faster after
- Hovering for team members, projects has to be according with UI-Kit
- Approach page. Iterative block. Centralized header
![selection_086](https://cloud.githubusercontent.com/assets/17002555/19685309/92d5debc-9ac4-11e6-8429-c0927605fd83.png)
- Our portfolio. Add smooth sliding
![selection_087](https://cloud.githubusercontent.com/assets/17002555/19685357/c3772b8e-9ac4-11e6-8da3-067883252846.png)
- Add border to avatars
![selection_088](https://cloud.githubusercontent.com/assets/17002555/19685571/0522ffda-9ac6-11e6-8f49-7598bab4a8e6.png)
- Unable ability to re-size by width
![selection_089](https://cloud.githubusercontent.com/assets/17002555/19685617/318389a0-9ac6-11e6-8d79-f35801e62134.png)

**Comment by SergeyKuryatnick** [comment]
Tested

Comments
**- Approach page:** no slider dots for "Our portfolio" carousel
**- Approach page:** "Our portfolio" carousel has no smooth sliding
**- General page:** Button "See how we do it" too states, that are looks non-different for user

**Comment by SergeyKuryatnick** [comment]
https://github.com/VS-work/vs-website/issues/145
https://github.com/VS-work/vs-website/issues/143
