### ISSUE TITLE
Tablets. Enhancements according with suggestions

### ISSUE THREAD

**Issue by bogdankatrych** [VS-work/vs-website#123]
- Services page. Reduce the size of images, centralized header and description
![selection_090](https://cloud.githubusercontent.com/assets/17002555/19685722/a015f678-9ac6-11e6-9928-6b2a2508d635.png)
- Team member. Check out resolution 1200. Has to fit 2 projects 
![selection_091](https://cloud.githubusercontent.com/assets/17002555/19685802/f447bd9e-9ac6-11e6-8689-f4f0d7e08e21.png)
- "Star sky" return back

**Comment by SergeyKuryatnick** [comment]
Tested

Comments
- Team Member page: there presented more then two projects at the page

Known issues:
https://github.com/VS-work/vs-website/issues/146
