### ISSUE TITLE
Our culture. Link "Culture" navigates to the bottom of the page "About Us"

### ISSUE THREAD

**Issue by SergeyKuryatnick** [VS-work/vs-website#149]
**WTR:**
1. Open https://vs-work.github.io/#/careers/2
2. Go to the bottom of the page to link "Culture"
3. Click on Culture link

**Result:** User navigates to the top of the page "About us"
**Expected result:** User navigates to the "Our culture" part at page "About Us"
![1477931719882](https://cloud.githubusercontent.com/assets/19388643/19862409/cef7bfea-9f98-11e6-9ef6-93b6cc22df20.jpg)

**Comment by SergeyKuryatnick** [comment]
Fixed

**Comment by daniloff200** [comment]
`https://vs-work.github.io/#/contact` if you here, and press **Our Culture** -> you will be redirected to about page, but on the top
It happened because of mistake in url ->` https://vs-work.github.io/#/about#out-culture`, but should be `https://vs-work.github.io/#/about#our-culture`
