### ISSUE TITLE
Contact Form. Careers. Phone field validation doesn't work

### ISSUE THREAD

**Issue by SergeyKuryatnick** [VS-work/vs-website#154]
**WTR:**
1. Open https://vs-work.github.io/#/careers/4
2. Fill form using valid phone number
3. Send email

**Result:**  Email not sent, phone number is not approved by server
**Expected result:** If user input wrong number - validation should show it
![1478270934289](https://cloud.githubusercontent.com/assets/19388643/20009921/f26f664e-a2ae-11e6-961a-2a896852b1d0.jpg)

**Comment by EvilAlexei** [comment]
Fixed
