### ISSUE TITLE
Desktop.Services page: `How we do it` section

### ISSUE THREAD

**Issue by bogdankatrych** [VS-work/vs-website#16]
Needs to implement `Simple content component` according with design mock-up

![selection_051](https://cloud.githubusercontent.com/assets/17002555/19116165/2c320ce6-8b1d-11e6-84c7-248a17d6bd40.png)

**Comment by SergeyKuryatnick** [comment]
Comments:
- Description text differ than in mockup, i think it's because texts is not ready yet

https://github.com/VS-work/vs-website/issues/67
