### ISSUE TITLE
Careers. Lists with responcibilities should end with dots

### ISSUE THREAD

**Issue by SergeyKuryatnick** [VS-work/vs-website#169]
**WTR:**
1. Open careers page
2. Open any pozition
3. Look at list with responcibilities

**Result:** list end with semicolon
**Expected result:** list end with dot
![dots](https://cloud.githubusercontent.com/assets/19388643/23646931/e3d2b596-031b-11e7-831c-adf8740f9c42.png)

**Comment by daniloff200** [comment]
![selection_126](https://cloud.githubusercontent.com/assets/13692220/24792284/ffadb81a-1b85-11e7-8ae0-4bfac051190d.png)
