### ISSUE TITLE
Desktop.About page: Section `Vacancies List`

### ISSUE THREAD

**Issue by bogdankatrych** [VS-work/vs-website#20]
Needs to implement:
- Title, description(with link)
- Grid with: {Vacancy name, link}

![selection_054](https://cloud.githubusercontent.com/assets/17002555/19147357/71768df6-8bc0-11e6-8fd6-c46771fc61ad.png)
- `View position` link route to `Vacancy page`
![selection_055](https://cloud.githubusercontent.com/assets/17002555/19147637/b2de1d76-8bc1-11e6-8c67-a4c7db6a22c4.png)

**Comment by daniloff200** [comment]
For About page : Done

For Careers page : In progress

**Comment by SergeyKuryatnick** [comment]
No link in description:
![1476694874911](https://cloud.githubusercontent.com/assets/19388643/19431517/707d345a-9461-11e6-8fd4-15d5065c9c04.jpg)
