### ISSUE TITLE
Desktop.Team member page: Implementation of `Project list component` 

### ISSUE THREAD

**Issue by bogdankatrych** [VS-work/vs-website#26]
Here we can see projects in which team member took part 
![selection_060](https://cloud.githubusercontent.com/assets/17002555/19158650/3496b53c-8bf2-11e6-9f90-88d6561ef2e9.png)

**Comment by bogdankatrych** [comment]
#25

**Comment by SergeyKuryatnick** [comment]
Think need to describe what this person do on each project.
![1476799701529](https://cloud.githubusercontent.com/assets/19388643/19481085/75a52f9c-9555-11e6-8b27-13f82a073ee5.jpg)

**Comment by SergeyKuryatnick** [comment]
Tested
