### ISSUE TITLE
Desktop.Internal project page (Case study) Implementation `Case study component` 

### ISSUE THREAD

**Issue by bogdankatrych** [VS-work/vs-website#27]
Needs to implement next reusable components: 
- menu
- title, description 
- background
- online link 
- link on behance

![selection_061](https://cloud.githubusercontent.com/assets/17002555/19158960/599c2abe-8bf3-11e6-947a-4785d2551c50.png)

![selection_065](https://cloud.githubusercontent.com/assets/17002555/19268256/094e7eaa-8fbc-11e6-84b8-ff97d094ef2b.png)

![selection_066](https://cloud.githubusercontent.com/assets/17002555/19268260/100d2aac-8fbc-11e6-98c7-04152eb99112.png)

**Comment by SergeyKuryatnick** [comment]
Tested
