### ISSUE TITLE
Desktop.Clients.Case study page.Similar projects block: Remove current project from similar list

### ISSUE THREAD

**Issue by bogdankatrych** [VS-work/vs-website#30]
This issue connected with #3 

If we choose Case study in similar project doesn't need display chosen project.
![selection_064](https://cloud.githubusercontent.com/assets/17002555/19193143/9c8ef306-8cb1-11e6-88a3-a57471f77fc3.png)

**Comment by SergeyKuryatnick** [comment]
Tested
