### ISSUE TITLE
Desktop.Home page: Particles js. stop working on route changing

### ISSUE THREAD

**Issue by bogdankatrych** [VS-work/vs-website#31]
This issue connected with #1

![selection_028](https://cloud.githubusercontent.com/assets/17002555/19193239/fb3f02f6-8cb1-11e6-91d2-40f1c7555f65.png)

**Comment by otelnov** [comment]
https://github.com/VS-work/vs-website/commit/80f8643a53d4b4f81aff0b125d29c03954ef9c7a
it should help

**Comment by SergeyKuryatnick** [comment]
Tested
