### ISSUE TITLE
Desktop.Comments component:Implementation of slider, title and description

### ISSUE THREAD

**Issue by bogdankatrych** [VS-work/vs-website#4]
This component has to be implemented on next pages: 
- Home
- Services
- Clients

We need to implement :
- Title, description 
- Slider for this section
- Pagination

![selection_039](https://cloud.githubusercontent.com/assets/17002555/19073585/722e3622-8a44-11e6-9b06-3afd2bbc6a99.png)

**Comment by SergeyKuryatnick** [comment]
Tested for the home page.
Is not ready yet for Clients and Services Pages.

**Comment by bogdankatrych** [comment]
Developers who will implemented on pages clients and services, just use the same source code.
