### ISSUE TITLE
Desktop. Implementation of forms.  

### ISSUE THREAD

**Issue by bogdankatrych** [VS-work/vs-website#40]
We have three places where need to implement forms: 
- On Contact page. 
![selection_067](https://cloud.githubusercontent.com/assets/17002555/19268653/48ebc390-8fbe-11e6-8e83-8637c1cc7533.png)
- Vacancy page 
![selection_034](https://cloud.githubusercontent.com/assets/17002555/19268700/9820fee4-8fbe-11e6-8dec-a19e95f71cf3.png)

- Case study page.
![selection_068](https://cloud.githubusercontent.com/assets/17002555/19268733/cb18629c-8fbe-11e6-8e45-6f61728bada7.png)

**Comment by SergeyKuryatnick** [comment]
Comments:
- On **Contact page** no info about location and contact email
- 

https://github.com/VS-work/vs-website/issues/59
https://github.com/VS-work/vs-website/issues/60
https://github.com/VS-work/vs-website/issues/61
https://github.com/VS-work/vs-website/issues/62
https://github.com/VS-work/vs-website/issues/63
https://github.com/VS-work/vs-website/issues/65
