### ISSUE TITLE
Desktop.Home page.`Thanks for partners` component: Implementation layout according with design mock-up

### ISSUE THREAD

**Issue by bogdankatrych** [VS-work/vs-website#5]
![selection_040](https://cloud.githubusercontent.com/assets/17002555/19073722/311ab57e-8a45-11e6-8d10-0d62317bf7cc.png)

We need to implement - Title, description, columns with valid HTML, pale-grey background

**Comment by SergeyKuryatnick** [comment]
Tested

Comments:
- icons is bit blurred
- text font is little bit different than in mockup
