### ISSUE TITLE
Desktop. Contact form. No icon in field "Add document"

### ISSUE THREAD

**Issue by SergeyKuryatnick** [VS-work/vs-website#61]
**WTR:**
1. Go to Contact page
2. Pay attention at field "Add document"

**Result:** No icon in field "Add document"
**Expected result:** Icon in field "Add document" displayed correctly
![1476353362124](https://cloud.githubusercontent.com/assets/19388643/19345266/48927de2-9146-11e6-8cd1-ba4c34f42b3c.jpg)

**Comment by daniloff200** [comment]
Seems to me it fixed

**Comment by SergeyKuryatnick** [comment]
Tested
