### ISSUE TITLE
Desktop. Careers page. Phone number filed. Make type= "number" 

### ISSUE THREAD

**Issue by SergeyKuryatnick** [VS-work/vs-website#68]
**WTR:**
1. Open Careers page
2. Inspect field "Your phone"
3. Pay attention at attribute "type"

**Result:** Attribute type is text
**Expected result:** Attribute type is number
![1476359768815](https://cloud.githubusercontent.com/assets/19388643/19348270/db982ee8-9155-11e6-869e-9d10ba99b873.jpg)

**Comment by bogdankatrych** [comment]
Leave it for now
