### ISSUE TITLE
Desktop.Header components

### ISSUE THREAD

**Issue by bogdankatrych** [VS-work/vs-website#8]
![selection_044](https://cloud.githubusercontent.com/assets/17002555/19112958/36c0a350-8b10-11e6-841d-2b86eb96c31a.png)

Needs to implement:
- reusable `menu component` 
- Text(white)
- Background image
- plain text(in black square block)

**Comment by SergeyKuryatnick** [comment]
Tested

Comments:
Implemented only on approach page
