### ISSUE TITLE
Desktop.Careers page: Implementation of Vacancy description page 

### ISSUE THREAD

**Issue by bogdankatrych** [VS-work/vs-website#81]
![selection_072](https://cloud.githubusercontent.com/assets/17002555/19438316/ef319ec4-9481-11e6-94a7-a1d53acbff3c.png)
![selection_073](https://cloud.githubusercontent.com/assets/17002555/19438319/f45feaea-9481-11e6-92f0-6ca7ed8b463f.png)

**Comment by SergeyKuryatnick** [comment]
Tested
