### ISSUE TITLE
Desktop. Contact. Let's talk page didn't redirect to Let's talk section

### ISSUE THREAD

**Issue by SergeyKuryatnick** [VS-work/vs-website#89]
**WTR:**
1. Open Contact page https://vs-work.github.io/#/contact
2. Go to the bottom of the page
3. Click on button Let's Talk

**Result:** Nothing happens
**Expected result:** User redirected to the section Let's talk
![1476796549660](https://cloud.githubusercontent.com/assets/19388643/19479253/7c35dd0e-954e-11e6-976b-207a46470a2c.jpg)

**Comment by daniloff200** [comment]
Connected with #78 . After merging #86 it should work too

**Comment by SergeyKuryatnick** [comment]
Could we do that the button redirect to the section Lets Talk, not on the top of the page?
