### ISSUE TITLE
Mobile.Home page: Reduce a quantity of projects until 2

### ISSUE THREAD

**Issue by bogdankatrych** [VS-work/vs-website#90]
Needs to display only two projects. The rest of projects hide. 
![selection_077](https://cloud.githubusercontent.com/assets/17002555/19479578/242d2bec-9550-11e6-9b4a-a2da00f05129.png)

**Comment by SergeyKuryatnick** [comment]
Not fixed, there is 8 projects displayed on Client page

**Comment by SergeyKuryatnick** [comment]
Fixed
