### ISSUE TITLE
Mobile.Services: Fix layout according with suggestions

### ISSUE THREAD

**Issue by bogdankatrych** [VS-work/vs-website#92]
Sequence of order: 
1)Image
2)Headline
3)Text

All elements has to be centralized

Now it looks ugly
![selection_078](https://cloud.githubusercontent.com/assets/17002555/19480433/04e40b9a-9553-11e6-831c-504ecf0659d0.png)

Feedback component: 
![selection_079](https://cloud.githubusercontent.com/assets/17002555/19481559/05264452-9557-11e6-93d2-1fd07932a83a.png)

- Remove logo of company
- Industry and Location blocks
- Centralized the rest info

**Comment by SergeyKuryatnick** [comment]
Only one comment should displayed on the page.

**Comment by SergeyKuryatnick** [comment]
Fixed
