### ISSUE TITLE
Mobile.About page.Our story component and Vacancy block

### ISSUE THREAD

**Issue by bogdankatrych** [VS-work/vs-website#96]
Reduce the size of text and figures, delete logo

![selection_081](https://cloud.githubusercontent.com/assets/17002555/19481997/6d5f7e02-9558-11e6-852f-b8dcb9d86819.png)

Remove black border
![selection_082](https://cloud.githubusercontent.com/assets/17002555/19482229/249ec4e2-9559-11e6-9f6a-3809975273ef.png)

**Comment by SergeyKuryatnick** [comment]
Fixed
