### ISSUE TITLE
Mobile.Contact: Fix layout according with suggestions

### ISSUE THREAD

**Issue by bogdankatrych** [VS-work/vs-website#97]
Forms which needs to fix located on pages:
- Contact
- Careers(vacancy page)
- Case study page

Order of sequence: 
- Let's talk block
- Form
![selection_083](https://cloud.githubusercontent.com/assets/17002555/19482761/b2402d1c-955a-11e6-9331-1988f5285aea.png)

**Comment by SergeyKuryatnick** [comment]
Elements are not centered
![1476965754730](https://cloud.githubusercontent.com/assets/19388643/19559355/18e235a0-96d8-11e6-85a1-56e17643535e.jpg)

**Comment by SergeyKuryatnick** [comment]
Fixed
